export const REGISTER = "REGISTER";
export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
export const ERROR = "ERROR";
export const BOOK_APPOINTMENT = "BOOK_APPOINTMENT";
export const GET_ALL_APPOINTMENT = "GET_ALL_APPOINTMENT";
export const GET_BY_ID_APPOINTMENT = "GET_BY_ID_APPOINTMENT";
export const UPDATE_APPOINTMENT = "UPDATE_APPOINTMENT";
export const DELETE_APPOINTMENT = "DELETE_APPOINTMENT";
export const GET_DOCTOR = "GET_DOCTOR";
export const GET_AVAILABLE_APPOINTMENT = "GET_AVAILABLE_APPOINTMENT";
export const DOCTOR_SEARCH = "DOCTOR_SEARCH";
export const SHOW_STATE = "SHOW_STATE";
export const DOCTOR_CITY = "DOCTOR_CITY";
export const DOCTOR_STATE = "DOCTOR_STATE";
export const GET_ALL_DOCTOR = "GET_ALL_DOCTOR";
export const GET_CONTACT_DETAILS = "GET_CONTACT_DETAILS";
export const FORGET_PASSWORD_REQUEST = "FORGET_PASSWORD_REQUEST";
export const FORGET_PASSWORD = "FORGET_PASSWORD";
export const GET_ALL_USERS = "GET_ALL_USERS";

export const GETBY_ID_USER = "GETBY_ID_USER";

export const DELETE_USER = "DELETE_USER";
export const BLOCK = "BLOCK";
export const UNBLOCK = "UNBLOCK";

export const GET_BYID_APPOINTMENT = "GET_BYID_APPOINTMENT";

export const CREATE_DOCTOR = "CREATE_DOCTOR";
export const UPDATE_DOCTOR = "UPDATE_DOCTOR";
export const DELETE_DOCTOR = "DELETE_DOCTOR";
